import type { Client, MetricData } from "./types"

export const MOCK_CLIENTS: Client[] = [
  {
    id: "c001",
    name: "Fernanda Lopes",
    company: "Acme Logística",
    plan: "enterprise",
    status: "active",
    owner: "Carlos M.",
    lastContact: "2026-05-30",
    slaConsumed: 22,
    mrr: 12400,
    nps: 9,
    tasks: 2,
  },
  {
    id: "c002",
    name: "Ricardo Alves",
    company: "Nexus Varejo",
    plan: "growth",
    status: "at-risk",
    owner: "Ana P.",
    lastContact: "2026-05-18",
    slaConsumed: 78,
    mrr: 4200,
    nps: 5,
    tasks: 5,
  },
  {
    id: "c003",
    name: "Patrícia Sousa",
    company: "Orbita Fintech",
    plan: "enterprise",
    status: "active",
    owner: "Carlos M.",
    lastContact: "2026-06-01",
    slaConsumed: 45,
    mrr: 18900,
    nps: 8,
    tasks: 0,
  },
  {
    id: "c004",
    name: "Thiago Martins",
    company: "Vertex Saúde",
    plan: "starter",
    status: "trial",
    owner: "Beatriz S.",
    lastContact: "2026-06-02",
    slaConsumed: 10,
    mrr: 490,
    nps: null,
    tasks: 3,
  },
  {
    id: "c005",
    name: "Camila Rocha",
    company: "Pico Edutech",
    plan: "growth",
    status: "at-risk",
    owner: "Ana P.",
    lastContact: "2026-05-10",
    slaConsumed: 91,
    mrr: 3100,
    nps: 4,
    tasks: 8,
  },
  {
    id: "c006",
    name: "Diego Carvalho",
    company: "Strata Indústria",
    plan: "enterprise",
    status: "active",
    owner: "Beatriz S.",
    lastContact: "2026-05-28",
    slaConsumed: 33,
    mrr: 22000,
    nps: 10,
    tasks: 1,
  },
  {
    id: "c007",
    name: "Larissa Mendes",
    company: "Apex Agro",
    plan: "starter",
    status: "churned",
    owner: "Carlos M.",
    lastContact: "2026-04-20",
    slaConsumed: 100,
    mrr: 0,
    nps: 2,
    tasks: 0,
  },
  {
    id: "c008",
    name: "Bruno Ferreira",
    company: "Crest Construção",
    plan: "growth",
    status: "active",
    owner: "Ana P.",
    lastContact: "2026-05-31",
    slaConsumed: 55,
    mrr: 5600,
    nps: 7,
    tasks: 2,
  },
  {
    id: "c009",
    name: "Juliana Costa",
    company: "Nexum Seguros",
    plan: "enterprise",
    status: "active",
    owner: "Beatriz S.",
    lastContact: "2026-06-01",
    slaConsumed: 18,
    mrr: 15200,
    nps: 9,
    tasks: 4,
  },
  {
    id: "c010",
    name: "Eduardo Nunes",
    company: "Prism Telecom",
    plan: "growth",
    status: "at-risk",
    owner: "Carlos M.",
    lastContact: "2026-05-14",
    slaConsumed: 83,
    mrr: 3800,
    nps: 5,
    tasks: 6,
  },
  {
    id: "c011",
    name: "Vanessa Lima",
    company: "Axis Moda",
    plan: "starter",
    status: "active",
    owner: "Ana P.",
    lastContact: "2026-05-29",
    slaConsumed: 40,
    mrr: 890,
    nps: 8,
    tasks: 1,
  },
  {
    id: "c012",
    name: "Rafael Barbosa",
    company: "Core Tecnologia",
    plan: "enterprise",
    status: "active",
    owner: "Beatriz S.",
    lastContact: "2026-05-27",
    slaConsumed: 27,
    mrr: 28000,
    nps: 9,
    tasks: 3,
  },
  {
    id: "c013",
    name: "Isabela Cardoso",
    company: "Flux Energia",
    plan: "growth",
    status: "trial",
    owner: "Carlos M.",
    lastContact: "2026-06-02",
    slaConsumed: 5,
    mrr: 2400,
    nps: null,
    tasks: 2,
  },
  {
    id: "c014",
    name: "Marcelo Teixeira",
    company: "Sigma RH",
    plan: "starter",
    status: "churned",
    owner: "Ana P.",
    lastContact: "2026-04-05",
    slaConsumed: 100,
    mrr: 0,
    nps: 3,
    tasks: 0,
  },
  {
    id: "c015",
    name: "Aline Araújo",
    company: "Valor Investimentos",
    plan: "enterprise",
    status: "active",
    owner: "Beatriz S.",
    lastContact: "2026-05-30",
    slaConsumed: 61,
    mrr: 32000,
    nps: 8,
    tasks: 5,
  },
  {
    id: "c016",
    name: "Gustavo Oliveira",
    company: "Bolt E-commerce",
    plan: "growth",
    status: "active",
    owner: "Carlos M.",
    lastContact: "2026-06-01",
    slaConsumed: 48,
    mrr: 6100,
    nps: 7,
    tasks: 3,
  },
  {
    id: "c017",
    name: "Priscila Santos",
    company: "Wave Marketing",
    plan: "starter",
    status: "at-risk",
    owner: "Ana P.",
    lastContact: "2026-05-16",
    slaConsumed: 74,
    mrr: 490,
    nps: 4,
    tasks: 4,
  },
  {
    id: "c018",
    name: "Henrique Dias",
    company: "Titan Logística",
    plan: "enterprise",
    status: "active",
    owner: "Beatriz S.",
    lastContact: "2026-05-29",
    slaConsumed: 30,
    mrr: 19500,
    nps: 10,
    tasks: 1,
  },
]

export const MOCK_METRICS: MetricData[] = [
  {
    label: "Clientes ativos",
    value: "142",
    change: +4.2,
    trend: [110, 115, 118, 122, 128, 135, 142],
    icon: "Users",
  },
  {
    label: "Tarefas abertas",
    value: "38",
    change: -12.1,
    trend: [55, 51, 48, 44, 42, 40, 38],
    icon: "CheckSquare",
  },
  {
    label: "SLA em risco",
    value: "7",
    change: +16.7,
    trend: [3, 4, 4, 5, 6, 6, 7],
    icon: "AlertTriangle",
  },
  {
    label: "NPS médio",
    value: "7.4",
    change: +2.8,
    trend: [6.8, 6.9, 7.0, 7.1, 7.2, 7.3, 7.4],
    icon: "TrendingUp",
  },
]
