import type { Client, MetricData, Task } from "./types"

export const MOCK_CLIENTS: Client[] = [
  {
    id: "c001",
    name: "Fernanda Lopes",
    company: "Acme Logística",
    plan: "enterprise",
    status: "active",
    owner: "Carlos M.",
    lastContact: "2026-05-30",
    slaConsumed: 22,
    mrr: 12400,
    nps: 9,
    tasks: 2,
  },
  {
    id: "c002",
    name: "Ricardo Alves",
    company: "Nexus Varejo",
    plan: "growth",
    status: "at-risk",
    owner: "Ana P.",
    lastContact: "2026-05-18",
    slaConsumed: 78,
    mrr: 4200,
    nps: 5,
    tasks: 5,
  },
  {
    id: "c003",
    name: "Patrícia Sousa",
    company: "Orbita Fintech",
    plan: "enterprise",
    status: "active",
    owner: "Carlos M.",
    lastContact: "2026-06-01",
    slaConsumed: 45,
    mrr: 18900,
    nps: 8,
    tasks: 0,
  },
  {
    id: "c004",
    name: "Thiago Martins",
    company: "Vertex Saúde",
    plan: "starter",
    status: "trial",
    owner: "Beatriz S.",
    lastContact: "2026-06-02",
    slaConsumed: 10,
    mrr: 490,
    nps: null,
    tasks: 3,
  },
  {
    id: "c005",
    name: "Camila Rocha",
    company: "Pico Edutech",
    plan: "growth",
    status: "at-risk",
    owner: "Ana P.",
    lastContact: "2026-05-10",
    slaConsumed: 91,
    mrr: 3100,
    nps: 4,
    tasks: 8,
  },
  {
    id: "c006",
    name: "Diego Carvalho",
    company: "Strata Indústria",
    plan: "enterprise",
    status: "active",
    owner: "Beatriz S.",
    lastContact: "2026-05-28",
    slaConsumed: 33,
    mrr: 22000,
    nps: 10,
    tasks: 1,
  },
  {
    id: "c007",
    name: "Larissa Mendes",
    company: "Apex Agro",
    plan: "starter",
    status: "churned",
    owner: "Carlos M.",
    lastContact: "2026-04-20",
    slaConsumed: 100,
    mrr: 0,
    nps: 2,
    tasks: 0,
  },
  {
    id: "c008",
    name: "Bruno Ferreira",
    company: "Crest Construção",
    plan: "growth",
    status: "active",
    owner: "Ana P.",
    lastContact: "2026-05-31",
    slaConsumed: 55,
    mrr: 5600,
    nps: 7,
    tasks: 2,
  },
  {
    id: "c009",
    name: "Juliana Costa",
    company: "Nexum Seguros",
    plan: "enterprise",
    status: "active",
    owner: "Beatriz S.",
    lastContact: "2026-06-01",
    slaConsumed: 18,
    mrr: 15200,
    nps: 9,
    tasks: 4,
  },
  {
    id: "c010",
    name: "Eduardo Nunes",
    company: "Prism Telecom",
    plan: "growth",
    status: "at-risk",
    owner: "Carlos M.",
    lastContact: "2026-05-14",
    slaConsumed: 83,
    mrr: 3800,
    nps: 5,
    tasks: 6,
  },
  {
    id: "c011",
    name: "Vanessa Lima",
    company: "Axis Moda",
    plan: "starter",
    status: "active",
    owner: "Ana P.",
    lastContact: "2026-05-29",
    slaConsumed: 40,
    mrr: 890,
    nps: 8,
    tasks: 1,
  },
  {
    id: "c012",
    name: "Rafael Barbosa",
    company: "Core Tecnologia",
    plan: "enterprise",
    status: "active",
    owner: "Beatriz S.",
    lastContact: "2026-05-27",
    slaConsumed: 27,
    mrr: 28000,
    nps: 9,
    tasks: 3,
  },
  {
    id: "c013",
    name: "Isabela Cardoso",
    company: "Flux Energia",
    plan: "growth",
    status: "trial",
    owner: "Carlos M.",
    lastContact: "2026-06-02",
    slaConsumed: 5,
    mrr: 2400,
    nps: null,
    tasks: 2,
  },
  {
    id: "c014",
    name: "Marcelo Teixeira",
    company: "Sigma RH",
    plan: "starter",
    status: "churned",
    owner: "Ana P.",
    lastContact: "2026-04-05",
    slaConsumed: 100,
    mrr: 0,
    nps: 3,
    tasks: 0,
  },
  {
    id: "c015",
    name: "Aline Araújo",
    company: "Valor Investimentos",
    plan: "enterprise",
    status: "active",
    owner: "Beatriz S.",
    lastContact: "2026-05-30",
    slaConsumed: 61,
    mrr: 32000,
    nps: 8,
    tasks: 5,
  },
  {
    id: "c016",
    name: "Gustavo Oliveira",
    company: "Bolt E-commerce",
    plan: "growth",
    status: "active",
    owner: "Carlos M.",
    lastContact: "2026-06-01",
    slaConsumed: 48,
    mrr: 6100,
    nps: 7,
    tasks: 3,
  },
  {
    id: "c017",
    name: "Priscila Santos",
    company: "Wave Marketing",
    plan: "starter",
    status: "at-risk",
    owner: "Ana P.",
    lastContact: "2026-05-16",
    slaConsumed: 74,
    mrr: 490,
    nps: 4,
    tasks: 4,
  },
  {
    id: "c018",
    name: "Henrique Dias",
    company: "Titan Logística",
    plan: "enterprise",
    status: "active",
    owner: "Beatriz S.",
    lastContact: "2026-05-29",
    slaConsumed: 30,
    mrr: 19500,
    nps: 10,
    tasks: 1,
  },
]

export const MOCK_TASKS: Task[] = [
  {
    id: "t001",
    title: "Renovar contrato enterprise",
    clientId: "c001",
    clientName: "Fernanda Lopes",
    company: "Acme Logística",
    priority: "high",
    status: "pending",
    assignee: "Carlos M.",
    dueDate: "2026-06-10",
    createdAt: "2026-05-28",
  },
  {
    id: "t002",
    title: "Agendar reunião de resgate",
    clientId: "c002",
    clientName: "Ricardo Alves",
    company: "Nexus Varejo",
    priority: "high",
    status: "overdue",
    assignee: "Ana P.",
    dueDate: "2026-05-25",
    createdAt: "2026-05-15",
  },
  {
    id: "t003",
    title: "Enviar relatório mensal de uso",
    clientId: "c003",
    clientName: "Patrícia Sousa",
    company: "Orbita Fintech",
    priority: "medium",
    status: "done",
    assignee: "Carlos M.",
    dueDate: "2026-06-01",
    createdAt: "2026-05-25",
  },
  {
    id: "t004",
    title: "Onboarding inicial — configuração",
    clientId: "c004",
    clientName: "Thiago Martins",
    company: "Vertex Saúde",
    priority: "high",
    status: "in-progress",
    assignee: "Beatriz S.",
    dueDate: "2026-06-05",
    createdAt: "2026-06-02",
  },
  {
    id: "t005",
    title: "Plano de ação para redução de SLA",
    clientId: "c005",
    clientName: "Camila Rocha",
    company: "Pico Edutech",
    priority: "high",
    status: "overdue",
    assignee: "Ana P.",
    dueDate: "2026-05-20",
    createdAt: "2026-05-08",
  },
  {
    id: "t006",
    title: "Revisão de uso e proposta de upsell",
    clientId: "c006",
    clientName: "Diego Carvalho",
    company: "Strata Indústria",
    priority: "low",
    status: "pending",
    assignee: "Beatriz S.",
    dueDate: "2026-06-20",
    createdAt: "2026-05-28",
  },
  {
    id: "t007",
    title: "Check-in trimestral de saúde",
    clientId: "c008",
    clientName: "Bruno Ferreira",
    company: "Crest Construção",
    priority: "medium",
    status: "pending",
    assignee: "Ana P.",
    dueDate: "2026-06-15",
    createdAt: "2026-05-31",
  },
  {
    id: "t008",
    title: "Apresentar nova funcionalidade de automação",
    clientId: "c009",
    clientName: "Juliana Costa",
    company: "Nexum Seguros",
    priority: "medium",
    status: "in-progress",
    assignee: "Beatriz S.",
    dueDate: "2026-06-08",
    createdAt: "2026-05-30",
  },
  {
    id: "t009",
    title: "Ligação de resgate urgente",
    clientId: "c010",
    clientName: "Eduardo Nunes",
    company: "Prism Telecom",
    priority: "high",
    status: "overdue",
    assignee: "Carlos M.",
    dueDate: "2026-05-22",
    createdAt: "2026-05-12",
  },
  {
    id: "t010",
    title: "Enviar pesquisa de satisfação NPS",
    clientId: "c011",
    clientName: "Vanessa Lima",
    company: "Axis Moda",
    priority: "low",
    status: "done",
    assignee: "Ana P.",
    dueDate: "2026-05-30",
    createdAt: "2026-05-20",
  },
  {
    id: "t011",
    title: "Proposta de expansão de licenças",
    clientId: "c012",
    clientName: "Rafael Barbosa",
    company: "Core Tecnologia",
    priority: "medium",
    status: "pending",
    assignee: "Beatriz S.",
    dueDate: "2026-06-18",
    createdAt: "2026-05-27",
  },
  {
    id: "t012",
    title: "Onboarding — integração via API",
    clientId: "c013",
    clientName: "Isabela Cardoso",
    company: "Flux Energia",
    priority: "high",
    status: "in-progress",
    assignee: "Carlos M.",
    dueDate: "2026-06-07",
    createdAt: "2026-06-02",
  },
  {
    id: "t013",
    title: "Atualizar documentação de acesso",
    clientId: "c015",
    clientName: "Aline Araújo",
    company: "Valor Investimentos",
    priority: "low",
    status: "pending",
    assignee: "Beatriz S.",
    dueDate: "2026-06-25",
    createdAt: "2026-05-30",
  },
  {
    id: "t014",
    title: "Revisão de SLA consumido",
    clientId: "c017",
    clientName: "Priscila Santos",
    company: "Wave Marketing",
    priority: "high",
    status: "overdue",
    assignee: "Ana P.",
    dueDate: "2026-05-28",
    createdAt: "2026-05-16",
  },
  {
    id: "t015",
    title: "Renovação de contrato anual",
    clientId: "c018",
    clientName: "Henrique Dias",
    company: "Titan Logística",
    priority: "medium",
    status: "pending",
    assignee: "Beatriz S.",
    dueDate: "2026-06-30",
    createdAt: "2026-05-29",
  },
]

export const MOCK_METRICS: MetricData[] = [
  {
    label: "Clientes ativos",
    value: "142",
    change: +4.2,
    trend: [110, 115, 118, 122, 128, 135, 142],
    icon: "Users",
  },
  {
    label: "Tarefas abertas",
    value: "38",
    change: -12.1,
    trend: [55, 51, 48, 44, 42, 40, 38],
    icon: "CheckSquare",
  },
  {
    label: "SLA em risco",
    value: "7",
    change: +16.7,
    trend: [3, 4, 4, 5, 6, 6, 7],
    icon: "AlertTriangle",
  },
  {
    label: "NPS médio",
    value: "7.4",
    change: +2.8,
    trend: [6.8, 6.9, 7.0, 7.1, 7.2, 7.3, 7.4],
    icon: "TrendingUp",
  },
]
